spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elasticsearch_demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8080

logging:
  level:
    org.springframework.data.elasticsearch: INFO # Use INFO in production, switch to DEBUG for development troubleshooting
    com.example.elasticsearchdemo: DEBUG # Use DEBUG for application code during development
